version: '3.8'

services:
  report-agent:
    build: .
    container_name: report-generator
    env_file:
      - .env
    ports:
        - "5000:5000"
    volumes:
      - ./artifact:/app/artifact
      - ./src:/app/src
      - ./main.py:/app/main.py
      - ./logs:/app/logs
#    environment:
#      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped